"""add_user_settings_column

Revision ID: d3b421f6bdb7
Revises: 6c96086c1ffc
Create Date: 2026-01-31 22:11:11.301383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd3b421f6bdb7'
down_revision: Union[str, Sequence[str], None] = '6c96086c1ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('settings', sqlite.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'settings')
    # ### end Alembic commands ###
